//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myCareer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employer_social
    {
        public int soc_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string facebook { get; set; }
        public string youtube { get; set; }
        public string twitter { get; set; }
        public string website { get; set; }
        public string google { get; set; }
    }
}
