//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myCareer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employer_info
    {
        public int emp_id { get; set; }
        public string company_name { get; set; }
        public Nullable<int> company_type { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string description { get; set; }
        public Nullable<int> reg_type { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string contact { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string status { get; set; }
        public string logo { get; set; }
        public Nullable<int> login_info { get; set; }
    }
}
