//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myCareer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        public int job_id { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> submission_date { get; set; }
        public Nullable<int> category { get; set; }
        public string description { get; set; }
        public string job_type { get; set; }
        public string job_level { get; set; }
        public string gender { get; set; }
        public Nullable<double> salaryfrom { get; set; }
        public Nullable<double> salaryto { get; set; }
        public Nullable<int> experience { get; set; }
        public string state { get; set; }
        public string district { get; set; }
        public string city { get; set; }
        public string postalcode { get; set; }
        public string full_address { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<int> openings { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> employer { get; set; }
        public string skills { get; set; }
    }
}
