//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myCareer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobseeker_education
    {
        public int jsed_id { get; set; }
        public string education_level { get; set; }
        public string edu_status { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> js_id { get; set; }
        public string institution { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
    }
}
