//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myCareer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int message_id { get; set; }
        public string sender_name { get; set; }
        public string sender_address { get; set; }
        public string sender_contact { get; set; }
        public string message1 { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> read_status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
