//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myCareer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myCareerEntities : DbContext
    {
        public myCareerEntities()
            : base("name=myCareerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<application> applications { get; set; }
        public virtual DbSet<company_type> company_type { get; set; }
        public virtual DbSet<employer_info> employer_info { get; set; }
        public virtual DbSet<interest> interests { get; set; }
        public virtual DbSet<job_categories> job_categories { get; set; }
        public virtual DbSet<jobseeker_info> jobseeker_info { get; set; }
        public virtual DbSet<nepal_district> nepal_district { get; set; }
        public virtual DbSet<registration_type> registration_type { get; set; }
        public virtual DbSet<shortlist> shortlists { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<js_experience> js_experience { get; set; }
        public virtual DbSet<jobseeker_education> jobseeker_education { get; set; }
        public virtual DbSet<message> messages { get; set; }
        public virtual DbSet<email_verification> email_verification { get; set; }
        public virtual DbSet<itemset> itemsets { get; set; }
        public virtual DbSet<job> jobs { get; set; }
        public virtual DbSet<tbl_cv> tbl_cv { get; set; }
        public virtual DbSet<employer_social> employer_social { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
