//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myCareer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cv
    {
        public int cv_id { get; set; }
        public Nullable<int> jobseeker_id { get; set; }
        public string file_loc { get; set; }
        public string cv { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string cv_details { get; set; }
    }
}
